### ISSUE TITLE
Problèmes Chimie

### ISSUE THREAD

**Issue by Tartapouet** [Les-Paumes-de-SS13/Paume-Station-2#2]
- Le juicer en chimie n'est pas la bonne machine, elle n'accepte pas les cristaux de phoron.
- Il manque un moyen de refroidir les chems.
- Il y a trop de cartridges dans le smartfridge

**Comment by Tartapouet** [comment]
J'ai ouvert un PR (#3) qui devrait régler ces 3 trucs. Je vous laisse voir si c'est bien fait.

**Comment by krell** [comment]
Tout est ok, j'ai merge la PR. Merci pour ta contribution.
