### ISSUE TITLE
Manque d'un Full Body Scanner en medbay

### ISSUE THREAD

**Issue by Tartapouet** [Les-Paumes-de-SS13/Paume-Station-2#5]
Il manque un Full Body Scanner `[obj/machinery/bodyscanner]` et sa console `[obj/machinery/body_scanconsole]` en baie médicale. 
Le scanner permet de déterminer l'emplacement précis des organes et/ou des os endommagés dans les patients.
Un outil absolument nécessaire au bon fonctionnement d'une baie médicale.

**Comment by krell** [comment]
Je prend le sujet, je vais créer une nouvelle salle. Il y aura des lits et des scanners avec leur console. On peut traiter ce genre de salle comme une sorte de salle de soins intensif.

**Comment by krell** [comment]
![Uploading image.png…]()

**Comment by krell** [comment]
![intensive care](https://user-images.githubusercontent.com/3148126/94375423-c2d9eb80-0113-11eb-896e-4b8da669f1c0.PNG)

**Comment by krell** [comment]
J'ai également ajouté un écran d'affichage du status du scanner en chirurgie pour que le chirurgien puisse disposer des données du patient.
