### ISSUE TITLE
Les skills de certaines catégories sont limitées à "Trained"

### ISSUE THREAD

**Issue by Tartapouet** [Les-Paumes-de-SS13/Paume-Station-2#7]
À la création de personnage, il est impossible de sélectionner **Experienced** ou **Master** dans certaines catégories (cf. screen).

![image](https://user-images.githubusercontent.com/63240676/94989211-62173c80-0573-11eb-808e-e22fe8b2c273.png)

C'est particulièrement un problème pour les opérations chirurgicales. Où il est nécessaire d'être **Experienced** en ***Anatomy*** et ***Medicine*** pour pouvoir opérer sans risque.

**Comment by Tartapouet** [comment]
Une troisième solution serait aussi de ne pas y toucher jusqu'à ce que la renfonte de la chaîne de commandement soit faite.

**Comment by krell** [comment]
En fouillant un peu je viens de me rendre compte que l'on peut faire cette modif sur le scope de la map au lieu du code générique du projet officiel. Je pense m'orienter vers cette solution pour éviter un conflit lors des intégrations des fichiers du projet officiel.
